export const countryList = [
  'Afeganistão', 'África do Sul', 'Albânia', 'Alemanha', 'Andorra', 'Angola', 'Anguila', 'Antígua e Barbuda',
  'Antilhas Holandesas', 'Arábia Saudita', 'Argélia', 'Argentina', 'Armênia', 'Aruba', 'Austrália', 'Áustria',
  'Azerbaijão', 'Bahamas', 'Bangladesh', 'Barbados', 'Barein', 'Bélgica', 'Belize', 'Benin', 'Bermuda',
  'Bielorrússia', 'Bolívia', 'Bósnia Herzegovina', 'Botsuana', 'Brasil', 'Brunei', 'Bulgária', 'Burkina Fasso',
  'Burundi', 'Butão', 'Cabo Verde', 'Camarões', 'Camboja', 'Canadá', 'Catar', 'Cazaquistão', 'Chade', 'Chile',
  'China', 'Chipre', 'Colômbia', 'Congo', 'Coréia do Norte', 'Coréia do Sul', 'Costa do Marfim', 'Costa Rica',
  'Croácia', 'Cuba', 'Curaçao', 'Dinamarca', 'Djibuti', 'Dominica', 'Egito', 'El Salvador', 'Emirados Árabes Unidos',
  'Equador', 'Eritréia', 'Eslováquia', 'Eslovênia', 'Espanha', 'Estados Unidos', 'Estônia', 'Etiópia', 'Fiji',
  'Filipinas', 'Finlândia', 'França', 'Gabão', 'Gâmbia', 'Gana', 'Gibraltar', 'Granada', 'Grécia', 'Groenlândia',
  'Guadalupe', 'Guam', 'Guatemala', 'Guiana', 'Guiana Francesa', 'Guiné', 'Guiné Equatorial', 'Guiné-Bissau', 'Haiti',
  'Holanda', 'Honduras', 'Hong Kong', 'Hungria', 'Iêmen', 'Ilha Bouvet', 'Ilha Minor Outlying', 'Ilha Norfolk',
  'Ilha Reunião', 'Ilha São Tomé e Príncipe', 'Ilhas Cayman', 'Ilhas Christmas', 'Ilhas Coco', 'Ilhas Comoro',
  'Ilhas Cook', 'Ilhas Falkland', 'Ilhas Faroe', 'Ilhas Heard & McDonald', 'Ilhas Mariana do Norte', 'Ilhas Marshall',
  'Ilhas Maurício', 'Ilhas Salomão', 'Ilhas Svalbard & Jan Mayan', 'Ilhas Turks e Caicos', 'Ilhas Virgens Americanas',
  'Ilhas Virgens Britânicas', 'Ilhas Wallis e Futuna', 'Índia', 'Indonésia', 'Inglaterra', 'Irã', 'Iraque', 'Irlanda',
  'Islândia', 'Israel', 'Itália', 'Iugoslávia', 'Jamaica', 'Japão', 'Jordânia', 'Kiribati', 'Kuwait', 'Laos', 'Lesoto',
  'Letônia', 'Líbano', 'Liberia', 'Líbia', 'Liechtenstein', 'Lituânia', 'Luxemburgo', 'Macedônia', 'Madagascar',
  'Malásia', 'Malauí', 'Maldivas', 'Mali', 'Malta', 'Marrocos', 'Martinica', 'Maurícia', 'Mauritânia', 'Mayotte',
  'México', 'Mianmar', 'Micronésia', 'Moçambique', 'Moldávia', 'Mônaco', 'Mongólia', 'Montenegro', 'Montserrat',
  'Namíbia', 'Nauru', 'Nepal', 'Nicarágua', 'Níger', 'Nigéria', 'Niue', 'Noruega', 'Nova Caledônia', 'Nova Zelândia',
  'Omã', 'Palau', 'Palestina', 'Panamá', 'Papua-Nova Guiné', 'Paquistão', 'Paraguai', 'Peru', 'Pitcairn',
  'Polinésia Francesa', 'Polônia', 'Porto Rico', 'Portugal', 'Quênia', 'Quirguistão', 'Russia', 'Tailândia', 'Taiwan', 'Tanzânia',
  'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Trindade e Tobago', 'Tunísia', 'Turcomenistão', 'Turks e Caicos',
  'Turquia', 'Tuvalu', 'Ucrânia', 'Uganda', 'Uruguai', 'Uzbequistão', 'Vanuatu', 'Venezuela', 'Vietnã', 'Zâmbia',
  'Zimbábue'
];
